# Generated by Django 6.1.1 on 2026-09-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name": "Новость", "verbose_name_plural": "Новости"},
        ),
    ]
