# Generated by Django 6.1.1 on 2026-09-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="category",
            field=models.CharField(
                choices=[
                    ("backend", "Backend"),
                    ("frontend", "Frontend"),
                    ("ai", "AI"),
                    ("cyber_security", "Cyber Security"),
                    ("cyber_sport", "Cyber Sport"),
                    ("game_development", "Game Development"),
                ],
                default="backend",
                max_length=35,
                verbose_name="Категория",
            ),
            preserve_default=False,
        ),
    ]
