# Generated by Django 6.1.1 on 2026-09-21 12:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_news_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="category",
            field=models.CharField(
                choices=[
                    ("backend", "Бэкенд"),
                    ("frontend", "Фронтенд"),
                    ("ai", "Искусственный интеллект"),
                    ("cyber_security", "Кибербезопасность"),
                    ("cyber_sport", "Киберспорт"),
                    ("game_development", "Разработка игр"),
                    ("other", "Разное"),
                ],
                max_length=35,
                verbose_name="Категория",
            ),
        ),
    ]
