# Generated by Django 6.1.1 on 2026-09-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_news_image_alter_news_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
        ),
    ]
