# Generated by Django 6.1.1 on 2026-09-22 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="category_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="news",
                to="news.category",
                verbose_name="Категория",
            ),
        ),
    ]
