# Generated by Django 6.1.1 on 2026-09-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0010_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_approved",
            field=models.BooleanField(
                default=True, verbose_name="Одобрено администратором"
            ),
        ),
    ]
